language: java
#jdk: openjdk14 #problems with sonar-maven-plugin
branches:
  only:
    - develop
    - "/^release-[0-999].[0-999]$/"
    - master
notifications:
  email:
    recipients:
      - manuel.martin.hornillos@alumnos.upm.es
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=mmartinhornillos -Dsonar.projectKey=MMartinHornillos_iwvg-devops-manuel-martin -Dsonar.login=$SONAR
deploy:
  provider: heroku
  api_key: $HEROKU
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(develop|master)$
  app:
    master: miw-iwvg-devops-manuel-martin
    develop: dev-iwvg-devops-manuel-martin
